version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  movieapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movieapp
    depends_on:
      - mongodb
    env_file:
      - .env.docker 
    environment:
      - PORT=8080
    ports:
      - '8080:8080'

volumes:
  mongodb_data:
